@moduleAddress = http://localhost:4000/api/v1/auth

### get tests
GET {{moduleAddress}}

### create test
POST {{moduleAddress}}/login
content-type: application/json

{
	"mobile": "93803398",
	"password": "mahdi"
}

# ### update test
# Patch {{moduleAddress}}/2700ee67-16b0-4638-9f2b-dd30ef6f3f5a
# content-type: application/json

# {
# 	"title": "update test documents"
# }

# ### update test
# DELETE  {{moduleAddress}}/2700ee67-16b0-4638-9f2b-dd30ef6f3f5a
# content-type: application/json
