services:
    postgresql:
        image: bitnami/postgresql:latest
        ports:
            - '5530:5432'
        volumes:
            - 'postgresql_data:/bitnami/postgresql'
        env_file:
            - './apps/root/prisma/.env'
    # .env needs POSTGRESQL_USERNAME, POSTGRESQL_PASSWORD, POSTGRESQL_DATABASE
volumes:
    postgresql_data:
        driver: local
